ALTER TABLE bookings ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS archived_reason TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS reactivated_at TIMESTAMPTZ;
